services:

  ping:
    container_name: ping
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ADDRESS: 0.0.0.0:8081
      PONG_ENDPOINT: pong:8082
      JAEGER_ADDRESS: jaeger:4318
    entrypoint: ["ping"]
    ports:
      - 8081:8081
  
  pong:
    container_name: pong
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ADDRESS: 0.0.0.0:8082
      JAEGER_ADDRESS: jaeger:4318
    entrypoint: ["pong"]
    ports:
        - 8082:8082

  jaeger:
    image: jaegertracing/all-in-one:1.53
    container_name: jaeger
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: :9411
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778 
      - 16686:16686 
      - 4317:4317 
      - 4318:4318 
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
  
  prometheus:
    image: prom/prometheus:v2.49.1
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  
  grafana:
    image: grafana/grafana:9.5.15
    container_name: grafana
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - 3000:3000
