scrape_configs:
  - job_name: "ping-collector"
    scrape_interval: 10s
    static_configs:
      - targets: ["ping:8081"]
  - job_name: "pong-collector"
    scrape_interval: 10s
    static_configs:
      - targets: ["pong:8082"]